### ISSUE TITLE
About the pre-trained model releasing

### ISSUE THREAD

**Issue by cheliu-computation** [pfriedri/wdm-3d#1]
Dear Authors,

Thanks for your impressive works.
Is any future to release the pre-trained model so it wil be really beneficial for this community.

I am working on generate realistic tumor on health volume, if I can use your pre-trained model, I would be able to generate tumor on synthetic volume, hence I could have infinite data to train a cls/seg models. If you have interest, I am very happy for collaboration.

**Comment by pfriedri** [comment]
Hello,

thanks for your interest in our work. 
We are actually planning to release pre-trained models for different datasets (starting with BraTs and LIDC-IDRI) and different resolutions. This may still take some time, but it is on our agenda.

Since our model is trained on BraTs, the generated images already contain tumors similar to those present in the original dataset. However, you could simply adopt the method to also generate the corresponding mask, or try to condition the generation process on a mask you define. If you are interested in discussing this further, just drop me an email.

**Comment by pfriedri** [comment]
We will release the model weights on **HuggingFace** 🤗 stay tuned!

https://huggingface.co/pfriedri/wdm-3d
